### ISSUE TITLE
Failed to compile.

### ISSUE THREAD

**Issue by muile-dev** [knowingharsh/react-coach-mark#17]
Hi Team, @knowingharsh 

Now, I can't import `react-coach-mark` after installing this lib

```js
Module not found: Error: Can't resolve 'react-coach-mark'
```

<img width="264" alt="Screen Shot 2022-11-09 at 17 41 35" src="https://user-images.githubusercontent.com/83914320/200809178-04a2a718-557e-47be-a4fd-ebbd0d8f9e74.png">

**Comment by rikusen0335** [comment]
Hello @muile-dev ! @knowingharsh is currently inactive, so I am here to support you.

Could you provide me what version are you using? Since recently I released 1.0.3 and it may causes this issue.
Also give it a try 1.0.2 if you are using 1.0.3.

**Comment by muile-dev** [comment]
Thanks @rikusen0335

**Comment by rikusen0335** [comment]
Have you figured it out?

**Comment by rikusen0335** [comment]
I released 1.0.4 now, you may fix that with the new version in case you haven't fixed yet.

**Comment by muile-dev** [comment]
the issue was fixed, thanks @rikusen0335

**Comment by rikusen0335** [comment]
@muile-dev Thanks for reporting! Now closing the issue.

Did you fix the issue by using 1.0.4?
